Fix errors when fetching deleted documents using the bulk api
When you try to fetch a deleted document, the doc attribute is set but has the value null. My commit fixes that and avoids the following exception 'NoMethodError: undefined method `database=' for nil:NilClass'.